### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by ConstCh** [bfil/scala-automapper#11]
I  got strange type mismatch error:

``` 
type mismatch;
    found   : TestFieldClass (in io.bfil.automapper.testcase.from)
    required: TestFieldClass (in io.bfil.automapper.testcase.to)  
        val result = automap(sourceFromDependency).to[testcase.to.TestClass]
```
It happends when i try to map classes with same names that are from dependency module (library)

You can check this test case https://github.com/4const/scala-automapper/commit/55f15718ab436c09f0fde0cf58e4b1d7c6a1a567

**Comment by bfil** [comment]
This should be fixed in version `0.6.2`.

Thanks for the detailed steps to reproduce this.

Somehow the Scala compiler was behaving in a weird way and triggering multiple macro expansions in these cases (maybe caused to the name clash between classes) and it was lying at compile time about whether a type was a case class or not (information the macro needs to rely on to generate the right code).

Somehow rearranging the conditionals in the macro seems to have fixed the issue. I'm not 100% sure why... maybe the optimizer was trying to be smart and caused the broken behaviour, who knows.
