### ISSUE TITLE
Dynamic mapping

### ISSUE THREAD

**Issue by sallareznov** [bfil/scala-automapper#3]
Hi,

I am currently trying to dynamically map a case class to another, but when I invoke the function `dynamicallyTo`, I have the following error:

```
[error] /Users/salla/workspace/toutatis/user-impl/src/main/scala/com/colisweb/toutatis/user/impl/UserServiceImpl.scala:97: value applyDynamic is not a member of com.bfil.automapper.PartialMapping[com.colisweb.toutatis.util.impl.entity.User]
[error] error after rewriting to com.bfil.automapper.`package`.automap[com.colisweb.toutatis.util.impl.entity.User](user).<applyDynamic: error>[UserResponse]("dynamicallyTo")
[error] possible cause: maybe a wrong Dynamic method signature?
```

The line of code is the following: 
```scala
private[this] def userToUserResponse(user: User): UserResponse = automap(user).dynamicallyTo[UserResponse](
      ...
  )
```

Howerer, the function `to` (static mapping) works fine. I am using the `0.4.0` version of the library and I imported it like this in my class:
```scala
import com.bfil.automapper._
```

Thanks in advance!

**Comment by sallareznov** [comment]
Hmm in fact, it compiles, but IntelliJ does not feel the same way.

**Comment by rfuerst87** [comment]
Hi @sallareznov 
Did you manage to make IntelliJ pick up `dynamicallyTo`? Just stumbled upon the same issue with version `0.6.0` and IntelliJ 2017.2.5

**Comment by bfil** [comment]
@rfuerst87 I've raised an issue with IntelliJ a while back about this:

https://youtrack.jetbrains.com/issue/SCL-12384

The issue is not really related to the automapper itself, IntelliJ just doesn't seem to be expanding dynamic methods with type parameters.

I've tried to have a look myself to sort it out in the IntelliJ plugin codebase but I didn't manage to fix the issue. I don't know the codebase very well, I've asked for some assistance but I'm still waiting for an answer.

Anyone willing to give it a try? ;)

https://github.com/JetBrains/intellij-scala/blob/idea173.x/scala/scala-impl/src/org/jetbrains/plugins/scala/lang/transformation/calls/ExpandDynamicCall.scala
